const productData = [
  {
    id: 1,
    name: 'Areia de Gato Grãos Finos',
    img: 'images/areiadegato.png',
    prices: [30.5, 69.9, 110.99],
    sizes: ['1 kg', '3 kg', '6 kg'],
    description: 'Areia Higiênica Viva Verde Grãos Finos para Gatos',
  },
  {
    id: 2,
    name: 'Areia de Gato Grãos Mistos',
    img: 'images/areiadegato2.png',
    prices: [30.5, 69.9, 110.99],
    sizes: ['1 kg', '3 kg', '6 kg'],
    description: 'Areia Higiênica Viva Verde Grãos Mistos para Gatos ',
  },
  {
    id: 3,
    name: 'Ração para Cães Adultos com Excesso de Peso',
    img: 'images/dog-food.png',
    prices: [124.99, 466.99, 761.9],
    sizes: ['1.5 kg', '7.5 kg', '10.5 kg'],
    description: 'Ração Royal Canin Veterinary Satiety para Cães Adultos de Porte Pequeno com Excesso de Peso',
  },
  {
    id: 4,
    name: 'Ração para Cães Sênior de Porte Grande e Gigante',
    img: 'images/dog-food2.png',
    prices: [77.9, 123.9, 261.9],
    sizes: ['5 kg', '10 kg', '15 kg'],
    description: 'Ração Premier Fórmula para Cães Sênior de Porte Grande e Gigante Sabor Frango',
  },
  {
    id: 5,
    name: 'Ração Calopsita para Pássaros',
    img: 'images/bird-food.png',
    prices: [23.99, 33.99, 149.99],
    sizes: ['310 g', '500 g', '5 kg'],
    description: 'Ração Reino das Aves Gold Mix Calopsita para Pássaros',
  },
  {
    id: 6,
    name: 'Alimento para Tartarugas',
    img: 'images/turtle-food.png',
    prices: [19.99, 37.99, 290.99],
    sizes: ['30 g', '75 g', '1 kg'],
    description: 'Alimento Alcon Club Reptolife para Tartarugas',
  },
  {
    id: 7,
    name: 'Ração para Jabutis',
    img: 'images/turtle-food2.png',
    prices: [79.07, 199.9, 329.9],
    sizes: ['280 g', '500 g', '1 kg'],
    description: 'Ração Extrusada Megazoo para Jabutis',
  },
  {
    id: 8,
    name: 'Suplemento para Tartaruga',
    img: 'images/turtle-food3.png',
    prices: [14.9, 32.9, 49.9],
    sizes: ['15 g', '20 g', '50 g'],
    description: 'Suplemento Alcon Tartaruga Reptocal',
  },
];

module.exports = productData;
